### ISSUE TITLE
ejabberd external authentication scripts missing

### ISSUE THREAD

**Issue by fancycode** [jsxc/jsxc.nextcloud#2]
The external authentication scripts for ejabberd (`auth_ejabberd_oc.php` and `auth_oc_user.php`) are no longer available starting with version 3.0.2 (or they have been moved/renamed and I couldn't find them). 

Are they no longer supported or are they maintained somewhere else now?

**Comment by sualko** [comment]
Yes, we stopped the maintenance for this hack. It was always problematic and a lot on the server side changed, so we had to do this step. For the future we are working on a more generic token based approach to allow nextcloud user to login into there xmpp account.

**Comment by fancycode** [comment]
Thanks for the information. Does that mean the old scripts no longer work with jsxc 3.0.2 or newer?

**Comment by sualko** [comment]
It's no issue with jsxc, it's about owncloud/nextcloud. As long as you use an older version of nc/oc it should work.

**Comment by sualko** [comment]
We decided that we will rewrite the authentication script from scratch, because we think there is a real need for this (as seen from all those requests). You will find the updated script in [jsxc/ejabberd-cloud-auth](https://github.com/jsxc/ejabberd-cloud-auth). To get an notification subscribe to this new repo.
